
public class ExceptionTest {
	public static void main(String[] args) {
		System.out.println(0); // 런타임 에러 : 실행중 발생하는 에러
//		Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
//		at ExceptionTest.main(ExceptionTest.java:4)
		
		
//		system.out.println(args[0]); // 컴파일 에러
//		Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
//			system cannot be resolved
//
//			at ExceptionTest.main(ExceptionTest.java:5)

	}
}

